### ISSUE TITLE
before change event

### ISSUE THREAD

**Issue by athena3071** [vasyabigi/angular-slick#82]
How can I use before change event of slick?
Here is what I implemented.
<slick arrows="true" autoplay="true" on-after-change="headerSliderChanged()">
...
</slick>

// js file
$scope.headerSliderChanged = function() {
    console.log('test');
}

but it doesn't print "test". What do I have to do?

**Comment by Muenze** [comment]
I have the same issue with all events.
The events are registered with slick by on<event> property, but that property doesn't exist in slick.
I have to register all events directly after slider.slick({}) call in the directive.
No one here has reported that before, so I can be doin it wrong, but I wasn't able to get a single event to work.

**Comment by Muenze** [comment]
I would pass the function headerSliderChanged to the on-after-change property of the slick tag, then manually register it by changing the directive, or clone the repo to an own github user, change it there and use it in bower. I have done it because several properties which exists in slick-carousel dont exist in angular-slick, and I didn't want to wait for the pull into master

**Comment by athena3071** [comment]
It seems I can use the solution of #50 
Instead of using OnBeforeChange, I use OnPrevChange event of idvorkin's repository.
